var x, y;
x=8, y=4;
x+=y;
document.getElementById("resultadosuma").innerHTML = "x += 4 es equivalente a x = x + 4  (siendo x=8) " + x;
x-=y;
document.getElementById("resultadoresta").innerHTML = "x -= 4 es equivalente a x = x - 4  (siendo x=12) " + x;
x*=y;
document.getElementById("resultadomultiplica").innerHTML = "x *= 4 es equivalente a x = x * 4  (siendo x=8) " + x;
x%=y;
document.getElementById("resultadoresto").innerHTML = "x %= 4 es equivalente a x = x % 4  (siendo x=32) " + x;
var x=5.5, y=4.003, z=3.999, mayor, menor, aleatorio,w, k;
x=Math.round(x);
document.getElementById("resultadoround").innerHTML = "El round de x que es 5.5 es " + x;
y=Math.ceil(y);
document.getElementById("resultadoceil").innerHTML = "El ceil de y = 4.003 es  " + y;
z=Math.floor(z);
document.getElementById("resultadofloor").innerHTML = "El floor de z =3.9999 es " + z;
mayor=Math.max(x,y,z)
document.getElementById("resultadomax").innerHTML = "El máximo es entre x, y, z es " + mayor;
menor=Math.min(x,y,z);
document.getElementById("resultadomin").innerHTML = "El menor entre x y z es  " + menor;
aleatorio=Math.round(Math.random()*100000);
document.getElementById("resultadorandom").innerHTML = "Número random de 0 a 99999 es:  " + aleatorio;
w=-13;
w=Math.abs(w);
document.getElementById("resultadoabs").innerHTML = "El absoluto de w=-13 es  " + w;
k=25;
k=Math.sqrt(k);
document.getElementById("resultadosqrt").innerHTML = "La raiz de k que es 25 es :  " + k;
